### ISSUE TITLE
Insufficient coverage and testing after recent merges

### ISSUE THREAD

**Issue by andreif** [dgorissen/pycel#104]
https://github.com/dgorissen/pycel/pull/98 introduced insufficient coverage. 
Enabling free Travis CI for this repo would really help. 

I had to make a few other fixes in order to make it through, see https://github.com/andreif/pycel/commit/511f9a10e870d25aa0615376e0d452e5a37a324f

**Comment by stephenrauch** [comment]
@dgorissen If have a few minutes to spare, could you hook this repo up to: https://travis-ci.com/ ?

**Comment by dgorissen** [comment]
Sure, let me have a look

**Comment by dgorissen** [comment]
Actually, I hooked up the repo but see that https://travis-ci.com/stephenrauch/pycel already exists. Is another one still need?

**Comment by stephenrauch** [comment]
@dgorissen  My repo is also using travis, but only works against my repo.  Your travis account however, appears to be hooked up, but is not working yet:

https://travis-ci.com/github/dgorissen/pycel/requests

Did you authorize a "plan" on travis?  It seems it is sometimes needed to say OK, to the free plan.

https://travis-ci.com/account/plan

Also, could also hook up: https://codecov.io/ ?

**Comment by dgorissen** [comment]
Thanks @stephenrauch, *facepalm*. Travis should be working now, I was able to trigger a successful build. Codecov should also be hooked up (https://app.codecov.io/gh/dgorissen/pycel/).  Let me know if anything else is needed.

**Comment by stephenrauch** [comment]
@dgorissen Everything looks great as can be seen on #107
