### ISSUE TITLE
re-license the parser/tokenizer under a license suitable for incorporation into openpyxl

### ISSUE THREAD

**Issue by phrrngtn** [dgorissen/pycel#11]
Dirk, would you be OK with re-licensing the parsing and tokenizing code under a license which is compatible with openpyxl?

**Comment by phrrngtn** [comment]
According to Charlie Clarke in https://bitbucket.org/openpyxl/openpyxl/issue/435/incomplete-read-with-extended-cells 
> Anything that's copyright only: MIT/BSD/Apache. openpyxl itself is MIT/PSF

**Comment by dgorissen** [comment]
I did not write the tokenizing/parser code and don't hold the copyright to it. Eric did and I just applied a small patch and integrated it. See the header of tokenizer.py.

**Comment by stephenrauch** [comment]
Pycel is now using the tokenizer from openpyxl, so this issue has been OBE (Overtaken by Events)
