### ISSUE TITLE
_CycleCell and _Cell may have problem

### ISSUE THREAD

**Issue by hellobiek** [dgorissen/pycel#118]
https://github.com/dgorissen/pycel/blob/6eb3c688d2941a4fac27e858a3d24ce30bed32ea/src/pycel/excelcompiler.py#L1062

https://github.com/dgorissen/pycel/blob/6eb3c688d2941a4fac27e858a3d24ce30bed32ea/src/pycel/excelcompiler.py#L1105

_Cell is base class，and _CycleCell is inherit from _Cell, what is the difference between this two value?

**Comment by stephenrauch** [comment]
I am afraid I do not understand the question.  _CycleCell has value as a `@property`

https://github.com/dgorissen/pycel/blob/6eb3c688d2941a4fac27e858a3d24ce30bed32ea/src/pycel/excelcompiler.py#L1111
