### ISSUE TITLE
split_address doesn't manages Excel NamedRanges

### ISSUE THREAD

**Issue by BenCEEME** [dgorissen/pycel#12]
Formula: 

=(1+gen_z)/(1+InputData!$G$50)-1

Contains an Excel Named Range called 'gen_z'

Throws error:

Exception: Invalid address format gen_z

Any idea on how to fix this?

**Comment by dgorissen** [comment]
If I remember correctly I did not add support for named ranges. Hence that is something that you would need to implement if you want it to work.

**Comment by BenCEEME** [comment]
From openpyxl it is possible to obtain the list of named ranges with:

workbook.get_named_ranges()

However it requires to load openpyxl and to read the Excel file with it, not quite the COM approach of PyCell.

**Comment by BenCEEME** [comment]
Ok would have any clue as to where it would be best to implement it in your code? (I'll send you a copy when I'm done)

**Comment by BenCEEME** [comment]
Report on progress: managed to build a small code to pull out all the DefinedNamedRanges from the Excel file using win32.com (cf. below). The trick is that one cannot access the Names object Item's Names and Values directly, it requires a loop from the Names count.

Now to make it into a def get_rangednames(self), from what I read in the code of PyCell, it seems to me that the file excelwrapper.py is the best place to implement.

Saying that the question now is of strategy to make the parser handle it. One option is to make Names recognizable in their own right, the second one is to make it a sub-branch of the function builder, the last one to create virtual cells (say "ZZZ") and store them up there.

How would you like your tea Sir?

def get_rangednames(self):
    rangednames = {}
    for i in range(self.app.ActiveWorkbook.Names.Count, 1):
        rangednames[str(Excel.ActiveWorkbook.Names.Item(i).Name)] = str(Excel.ActiveWorkbook.Names.Item(i).Value)
    return rangednames

**Comment by dgorissen** [comment]
Its been eons since I wrote that code but my gut feeling is that the cleanest way is for to make names recognisable in their on right. So before the parser throws an invalid cell name error (or similar) it checks if its actually a defined range, and if so, replaces the name with the actual cell range.

**Comment by BenCEEME** [comment]
thank you, working on it.

please find the final version of the excelwrapper.py implement to recognize rangednames.
improves significantly the upload speed vs. previous:

    def get_rangednames(self):
        self.rangednames = np.zeros(shape = (int(self.app.ActiveWorkbook.Names.Count),1), dtype=[('id', 'int_'), ('name', 'S200'), ('formula', 'S200')])
        for i in range(0, self.app.ActiveWorkbook.Names.Count):
            self.rangednames[i]['id'] = int(i+1)       
            self.rangednames[i]['name'] = str(self.app.ActiveWorkbook.Names.Item(i+1).Name)        
            self.rangednames[i]['formula'] = str(self.app.ActiveWorkbook.Names.Item(i+1).Value)
        return self.rangednames

**Comment by dgorissen** [comment]
Thanks. Please issue a pull request.

**Comment by BenCEEME** [comment]
Ok.

**Comment by BenCEEME** [comment]
Pull request issued.
