### ISSUE TITLE
win32.com cannot acquire all Named Ranges

### ISSUE THREAD

**Issue by BenCEEME** [dgorissen/pycel#14]
I have separated this issue from previous on Named Ranges owing to the need of structural changes to Pycell prior to overcome this.

Some named ranges specified in Office Open XML cannot be read from win32.com

E.g. take the name 'test' which formula is '$A'

This means that it refers to the cell in column $A on the same line where the cell in which this name is used. E.g. if 'test' representing '$A' is used in B4 then $A means $A4, if 'test' representing '$A' is used in G5 then 'test'  means '$A5', if 'test' representing '$A' is used in ZZ4 and ZZ5 then '$A' means '$A4' and '$A5' respectively.

When read from the NameManager in Excel, it will appear as $A + the  line in which the cursor was when the file was last saved and not $A. Say the cursor was on AB18 then it will appear as $A18. Using win32.com it will not even appear at all in the list of named ranges.

This implies that structurally PyCell must evolve from accessing the COM of Excel to reading the underlying XML. There is a program called openpyxl that just does that. I saw from the log of discussions on Pycell that a merger of the programs was being discussed. Did this proceed?

**Comment by dgorissen** [comment]
No nothing happened to my knowledge.

**Comment by BenCEEME** [comment]
Ok thanks.
New version posted this morning enables openpyxl acquisition of rangednames, shuffled win.32 version back to get_rangednames(self).
