### ISSUE TITLE
excelformula._parse_to_rpn crashes with space after "=" in formula

### ISSUE THREAD

**Issue by mrludens** [dgorissen/pycel#43]
excelformula._parse_to_rpn raise Exception with the formula "= (1,5 * (1 + B11 *B3 ^ B12) + 5) + 10" and worked correctly when I removed the space after the equal sign: "=(1,5 * (1 + B11 *B3 ^ B12) + 5) + 10". Excel works fine in either case.

**Comment by stephenrauch** [comment]
Thanks so much for reporting this. 

I was able to duplicate and fix. There is a fix available [here](https://github.com/stephenrauch/pycel/commit/b06aa9dd06a282fb5149bf0b577aeaaf5d397e0d):
```
pip3 install git+git://github.com/stephenrauch/pycel.git@b06aa9dd06a282fb5149bf0b577aeaaf5d397e0d
```

I should be able to get a release to PiPY in the next few days.
