### ISSUE TITLE
Unbounded Range Addresses (ie: A:B or 1:2) broken

### ISSUE THREAD

**Issue by ftune** [dgorissen/pycel#45]
processing a xlsx file like this
```
a	f	a	f
b	g		
c	h		
d	i		
e	j		

```
The 'f' on sheet1!D1=vlookup(C1,A:B,2,FALSE).
And got 
```

  File "C:\ProgramData\Anaconda3\lib\site-packages\pycel-1.0b6-py3.6.egg\pycel\excelcompiler.py", line 557, in build_range
    if cell_address.address not in self.cell_map:

AttributeError: 'str' object has no attribute 'address'
```
It seems that it cannot run the str formula, but it do support something like A1&B1, (the & connector in Excel).
Is there any ways to support all the formula in Excel ?
If it's impossible then just add some description in the readme.

**Comment by stephenrauch** [comment]
Thanks for reporting this.  I have been able to duplicate it.  While waiting for a fix, if you were to remove the column range `A:B` and replace with something like: `A1:B20`  eg:

```
=vlookup(C1,A1:B20,2,FALSE)
```
it would work.
