### ISSUE TITLE
Binder Notebook Example not Working

### ISSUE THREAD

**Issue by mfastudillo** [dgorissen/pycel#60]
#### What actually happened

I tried to run the pycel [example ](https://hub-binder.mybinder.ovh/user/stephenrauch-pycel-hughsbtq/notebooks/notebooks/example.ipynb)on binder but it gave an error ``NameError: name 'c' is not defined`. I think the example is missing some parts.

best, 

Miguel

**Comment by stephenrauch** [comment]
Unable to duplicate: https://hub.gke.mybinder.org/user/stephenrauch-pycel-g0aoufji/notebooks/notebooks/example.ipynb worked fine for me.

**Comment by mfastudillo** [comment]
maybe I launched binder from the wrong link. I used this one that is pointed in the readme
https://mybinder.org/v2/gh/stephenrauch/pycel/master?filepath=notebooks%2Fexample.ipynb

**Comment by stephenrauch** [comment]
Thanks for reporting this.  You were correct, there were pieces missing.  Don't understand why it initially looked ok at my end.  I was able to resolve on a local Jupyter instance.
