### ISSUE TITLE
TypeError with iferror in special case

### ISSUE THREAD

**Issue by tinkermachine** [dgorissen/pycel#77]
In the event an iferror formula does not have a second argument but has a valid first argument, I am getting a `TypeError: iferror() missing 1 required positional argument: 'value_if_error'
Eval: iferror(_C_("Sheet1!A1") / _C_("Sheet1!A2"))`

For e.g. a simple formula such as =iferror(12/3,) which works in excel will result in the above error.

**Comment by stephenrauch** [comment]
Thanks for reporting this. I have been able to duplicate it, and should have a fix before too long.
