### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by andreif** [dgorissen/pycel#80]
There is a reference to undefined attribute. Should it be `._node` instead?

https://github.com/dgorissen/pycel/blob/146e198cdc73f63a63cbeb7743d35888b29229aa/src/pycel/excelcompiler.py#L677-L678

Same in https://github.com/dgorissen/pycel/blob/146e198cdc73f63a63cbeb7743d35888b29229aa/src/pycel/excelformula.py#L245

**Comment by stephenrauch** [comment]
Check your version of networkx. I suspect it is < 2.0.0.

**Comment by andreif** [comment]
```
networkx==2.4
openpyxl==2.6.2
pycel==1.0b21
```

**Comment by andreif** [comment]
Using `_node` seems working fine.

**Comment by andreif** [comment]
Or should it be `nodes`?

**Comment by stephenrauch** [comment]
Looks like networkx 2.4 just got released yesterday.  It will be a few days before I can investigate this.  In the mean time I would suggest trying networkx version < 2.4.

**Comment by stephenrauch** [comment]
@andreif, Thanks for taking the time to report this.  Should be good to go.
