### ISSUE TITLE
MATCH and VLOOKUP issue

### ISSUE THREAD

**Issue by tinkermachine** [dgorissen/pycel#81]
Facing some errors with MATCH and VLOOKUP in the attached sheet.

[vlookup_temp.xlsx](https://github.com/dgorissen/pycel/files/3741780/vlookup_temp.xlsx)

If I set value for C11 to "Arena":

1. pycel's result for MATCH in C12 is 3, it should be 2 (MATCH running at 1 match type)
2. pycel's result for VLOOKUP in C13 is 3, it should be 2 (VLOOKUP running waicth TRUE approx match

**Comment by stephenrauch** [comment]
From the [Docs for Vlookup](https://support.office.com/en-us/article/vlookup-function-0bbc8083-26fe-4963-8ab8-93a18ad188a1): 

> If range_lookup is TRUE or left out, the first column needs to be sorted alphabetically or numerically. If the first column isn't sorted, the return value might be something you don't expect. Either sort the first column, or use FALSE for an exact match.

And the [Docs for Match](https://support.office.com/en-us/article/MATCH-function-E8DFFD45-C762-47D6-BF89-533F4A37673A):

> MATCH finds the largest value that is less than or equal to lookup_value. The values in the lookup_array argument must be placed in ascending order, for example: ...-2, -1, 0, 1, 2, ..., A-Z, FALSE, TRUE.

Basic issue is that they likely do, and pycel definitely does, a binary search to speed things up.  This means the lookup data must be sorted to work correctly.
