### ISSUE TITLE
AssertionError during set_value()

### ISSUE THREAD

**Issue by hoffman32** [dgorissen/pycel#93]
I have the next Issue:

AssertionError                            Traceback (most recent call last)
<ipython-input-7-fae5e63ebdce> in <module>
----> 1 excel.set_value('Estados Financieros (1)!F377', 1200)
      2 print("D1 is {}".format(excel.evaluate('Resumen (1)!D13')))

~\Anaconda3\lib\site-packages\pycel\excelcompiler.py in set_value(self, address, value, set_as_range)
    417         elif address not in self.cell_map:
    418             address = AddressRange.create(address).address
--> 419             assert address in self.cell_map

Please help me

**Comment by stephenrauch** [comment]
Before setting a cell value, the cell needs to be put in to the cell map.  To put a value into the cell map you can evaluate the address, or an address that references it.

You can also use the `validate_calcs()` method to populate the needed cell_map entries for any desired output cells.
